### ISSUE TITLE
Neighborhood Similarity

### ISSUE THREAD

**Issue by dice89** [AgreementMakerLight/AML-Project#1]
Hi there,

I'm  writing my masters thesis in the area of ontology matching and therefore had a look at your code especially on your structural matchers. And In my opinion there is a tiny bug in line 151 and 152

```
parentTotal += input.getSimilarity(i,j) /
Math.sqrt((rels.getDistance(sId,i) + rels.getDistance(tId, j))*0.5);
```
in my opinion it should state 

```
parentSim += input.getSimilarity(i,j) /
Math.sqrt((rels.getDistance(sId,i) + rels.getDistance(tId, j))*0.5);
```

Just a small clue, to further improve your software

Best wishes

Alex

**Comment by AgreementMakerLight** [comment]
Hi Alex,

You are right!
I've corrected the bug.
Many thanks for your feedback, and for your interest in AML!
Good luck with your masters!

Best,

Daniel
