### ISSUE TITLE
Loading of ontologies takes forever

### ISSUE THREAD

**Issue by LukasK** [AgreementMakerLight/AML-Project#10]
Hi,
when I try to load two ontologies (.owl), the program just stalls. Size does not seem to matter, it also happens with very small ones. I observed this behaviour with the latest .jar. Is this a known problem?

**Comment by DanFaria** [comment]
Hi,
I've had one student report the program taking long to open ontologies, which at the time I attributed to the ontologies including a number of imports (which can take time to load, especially with a slow connection). However, I'm not so sure now, given that I've been unable to replicate this and given your complaint. The latest .jar runs fine in all computers I've tested (Windows 10 laptop, Windows 7 desktop, and Ubunto desktop).
Could you tell me exactly in what conditions (CPU, memory, OS, Java version, ontologies and whether they include imports) you experienced this problem and how long did the ontologies take to load?

Thanks in advance!
