### ISSUE TITLE
maven.yeezhao.com not auth 

### ISSUE THREAD

**Issue by wangkun-king** [AgreementMakerLight/AML-Project#11]
http://maven.yeezhao.com:8081/nexus/content/groups/public/  without user&password
 Could not resolve dependencies  gephi

**Comment by AgreementMakerLight** [comment]
My apologies for this issue. We have been aware that some of the Maven dependencies were no longer available for some time, and we added them to the git repository as a temporary fix, but we forgot to update the pom.xml file accordingly.
We have now done so, and the issue should be solved, if not in the ideal manner.
