### ISSUE TITLE
Building AML

### ISSUE THREAD

**Issue by reinoldus** [AgreementMakerLight/AML-Project#12]
For those trying to get AML-Build:

All you have todo is replace the paths according to where you have checked out the repo.

EDIT - Clarification:
You have to add the "systemPath"-Tag for each dependency that is not found by maven, like so:

```
    <dependency>
      <groupId>uk.ac.shef.wit</groupId>
      <artifactId>simmetrics</artifactId>
      <version>1.6.2</version>
<scope>system</scope>
<systemPath>/home/ubuntu/git/AML-Project/AgreementMakerLight/src/lib/simmetrics.jar</systemPath>
    </dependency>
```

This will make maven look into that path before trying to download it since the repo needs an authentification for some reason. The libraries are provided within this git repository, so it should work.

```
<project xmlns="http://maven.apache.org/POM/4.0.0" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>aml</groupId>
  <artifactId>aml</artifactId>
  <packaging>jar</packaging>
  <version>2.1-SNAPSHOT</version>

  <name>AgreementMakerLight</name>
  <url>http://somer.fc.ul.pt/aml.php</url>

	<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>
<properties>
    <maven.compiler.source>1.6</maven.compiler.source>
    <maven.compiler.target>1.6</maven.compiler.target>
  </properties>
  <build>
    <sourceDirectory>${basedir}/src</sourceDirectory>
  
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>2.4</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <dependencyReducedPomLocation>${project.build.directory}/dependency-reduced-pom.xml</dependencyReducedPomLocation>
              <filters>
                <filter>
                  <artifact>*:*</artifact>
                  <excludes>
                    <exclude>META-INF/*.SF</exclude>
                    <exclude>META-INF/*.DSA</exclude>
                    <exclude>META-INF/*.RSA</exclude>
                  </excludes>
                </filter>
              </filters>
              <!-- Additional configuration. -->
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <mainClass>aml.Main</mainClass>
                </transformer>
              </transformers>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>commons-lang</groupId>
      <artifactId>commons-lang</artifactId>
      <version>2.6</version>
    </dependency>
    <dependency>
      <groupId>dom4j</groupId>
      <artifactId>dom4j</artifactId>
      <version>1.6.1</version>
    </dependency>
    <dependency>
      <groupId>org.semanticweb.elk</groupId>
      <artifactId>elk-owlapi-standalone</artifactId>
      <version>0.4.1</version>
      <classifier>bin</classifier>
    </dependency>
    <dependency>
      <groupId>org.gephi</groupId>
      <artifactId>gephi-toolkit</artifactId>
      <version>0.8.2</version>
      <scope>system</scope>
      <systemPath>/home/ubuntu/git/AML-Project/AgreementMakerLight/src/lib/gephi-toolkit.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>edu.smu.tspell.wordnet</groupId>
      <artifactId>jaws</artifactId>
      <version>1.3.3</version>
      <scope>system</scope>
      <systemPath>/home/ubuntu/git/AML-Project/AgreementMakerLight/src/lib/jaws.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>log4j</groupId>
      <artifactId>log4j</artifactId>
      <version>1.2.17</version>
    </dependency>
    <dependency>
      <groupId>com.memetix</groupId>
      <artifactId>microsoft-translator-java-api</artifactId>
      <version>0.6.2</version>
      <type>jar</type>
    </dependency>
    <dependency>
      <groupId>net.sourceforge.owlapi</groupId>
      <artifactId>owlapi-distribution</artifactId>
      <version>3.4.10</version>
    </dependency>
	<dependency>
	    <groupId>com.github.firemaples</groupId>
	    <artifactId>microsoft-translator-java-api</artifactId>
	    <version>v0.8.6</version>
	</dependency>
    <dependency>
      <groupId>uk.ac.shef.wit</groupId>
      <artifactId>simmetrics</artifactId>
      <version>1.6.2</version>
<scope>system</scope>
<systemPath>/home/ubuntu/git/AML-Project/AgreementMakerLight/src/lib/simmetrics.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>org.swinglabs.swingx</groupId>
      <artifactId>swingx-all</artifactId>
      <version>1.6.4</version>
    </dependency>
  </dependencies>
</project>
```

**Comment by eliohb** [comment]
i am trying to build the project but i have got the following error any advice
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:19 min
[INFO] Finished at: 2019-02-26T11:34:16+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project aml: Could not resolve dependencies fo
r project aml:aml:jar:2.1-SNAPSHOT: Failed to collect dependencies at org.gephi:
gephi-toolkit:jar:0.8.2: Failed to read artifact descriptor for org.gephi:gephi-
toolkit:jar:0.8.2: Could not transfer artifact org.gephi:gephi-toolkit:pom:0.8.2
 from/to maven.yeezhao.com (http://maven.yeezhao.com:8081/nexus/content/groups/p
ublic/): Connection reset -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException

**Comment by EngyNasr** [comment]
I am trying to and i have the same issue, and i thinks thats because the link http://maven.yeezhao.com:8081/nexus/content/groups/public/,  needs a user name and a password to download the gephi-toolkit:jar:0.8.2

I am still searching for a solution, please let me know if you find one, thanks in advance :)

**Comment by reinoldus** [comment]
I think what I was trying to say back then is that you can get it build, if you replace the following dependcies:
```
    <dependency>
      <groupId>org.swinglabs.swingx</groupId>
      <artifactId>swingx-all</artifactId>
      <version>1.6.4</version>
    </dependency>
```
With the one that are provided in the repos:
```
<systemPath>/home/ubuntu/git/AML-Project/AgreementMakerLight/src/lib/simmetrics.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>org.swinglabs.swingx</groupId>
      <artifactId>swingx-all</artifactId>
      <version>1.6.4</version>
    </dependency>
```

By adding this systemPath, maven will find the file on your file system.

**Comment by EngyNasr** [comment]
Ohh, thank you so much, it really helped, its running now, thanks a lot 
The only update is to use Source and target option 7 or later instead if 6  

Thanks a lot :)

**Comment by AgreementMakerLight** [comment]
My apologies for this issue. We have been aware that some of the Maven dependencies were no longer available for some time, and we added them to the git repository as a temporary fix, but we forgot to update the pom.xml file accordingly.
We have now done so, and the issue should be solved, if not in the ideal manner.

**Comment by EngyNasr** [comment]
Thank you so much for your reply, I have tried to clone to git again but I
could not, can you please help me out with this too


[image: image.png]


Thanks a lot & Kind Regards,
Engy Nasr

**Comment by AgreementMakerLight** [comment]
Could you please detail the problem you are having?

**Comment by EngyNasr** [comment]
Thanks again for your kind reply, the problem is that when i clone to AML
github repository, I got this message "This Folder contains files. Git can
only clone to empty folders", so I downloaded the folder as a zip and its
working fine now.
Except for the property matcher in the custom match or the automatic match,
i got the exceptions attached. But when i remove the property matcher from
the custom match, AML works and gets out the alignments.

Thanks a lot for your great help and support
Best Regards;
Engy Nasr

**Comment by AgreementMakerLight** [comment]
@EngyNasr:
I'm not sure what you were trying to do with git clone, but you can't really clone TO AML's github repository, you can only clone FROM it, by typing "git clone https://github.com/AgreementMakerLight/AML-Project.git" in the directory of your computer where you want the project, and making sure you don't already have an 'AML-Project' directory there. 

Could you please detail the exception you got with Property Matcher?
Please bear in mind that I'm receiving your contact through github issues, and thus can't see any attachments you send via email.

**Comment by EngyNasr** [comment]
Thanks again :)

1)  for the cloning I was cloning from as you just explained  by typing
"git clone https://github.com/AgreementMakerLight/AML-Project.git" in the
directory of my computer, but I am getting this message "This Folder
contains files. Git can only clone to empty folders".

2)  For the automatic match, I get the following exception
Exception in thread "Thread-29" java.lang.NoClassDefFoundError:
edu/smu/tspell/wordnet/WordNetDatabase
 at aml.knowledge.WordNet.<init>(WordNet.java:47)
 at aml.util.NameSimilarity.<init>(NameSimilarity.java:35)
 at aml.match.HybridStringMatcher.<init>(HybridStringMatcher.java:68)
 at aml.match.AutomaticMatcher.matchIndividuals(AutomaticMatcher.java:376)
 at aml.match.AutomaticMatcher.match(AutomaticMatcher.java:98)
 at aml.AML.matchAuto(AML.java:712)
 at aml.ui.AMLMenuBar.run(AMLMenuBar.java:265)
 at java.base/java.lang.Thread.run(Thread.java:835)

3) For the custom match, if the property matcher is chosen, i get the
following exception
Exception in thread "Thread-31" java.lang.NoClassDefFoundError:
edu/smu/tspell/wordnet/WordNetDatabase
 at aml.knowledge.WordNet.<init>(WordNet.java:47)
 at aml.util.NameSimilarity.<init>(NameSimilarity.java:35)
 at aml.match.HybridStringMatcher.<init>(HybridStringMatcher.java:68)
 at aml.match.ManualMatcher.match(ManualMatcher.java:114)
 at aml.AML.matchManual(AML.java:771)
 at aml.ui.MatchOptions.run(MatchOptions.java:194)
 at java.base/java.lang.Thread.run(Thread.java:835)

I don't know how to thank you for all your great effort and support, thanks
a lot

**Comment by AgreementMakerLight** [comment]
@EngyNasr:

1) I have just checked that I git clone works for me. Have you checked that the directory where you are calling the command from is: a) empty and b) a directory where you (or git) have write permissions? I cannot think of anything else that would cause this.

2 & 3) That is a weird error. If the jaws.jar library were missing from your classpath altogether, you should be getting an unresolved compilation error, rather than a NoClassDefFoundError.
- How are you running AML: from Eclipse, from a Jar? 
- Which version of Java are you using? The jaws library is a bit old and it may not run with Java 10, so if that is what you are running, I would suggest that you try running the program using Java 8 (though 9 should be fine as well).

**Comment by EngyNasr** [comment]
Yeah thank you, I have solved the first problem regarding the cloning.

For the exceptions I am running AML from the JAR file using Java 12, I will
run using Java 8,  thanks a lot :)

**Comment by AgreementMakerLight** [comment]
@EngyNasr:
If you don't want to do any development on AML, just running the JAR, I suggest getting the last release (https://github.com/AgreementMakerLight/AML-Project/releases/tag/v3.1) instead of cloning the project then building it locally. I cannot guarantee it will run on Java 10 or up (it might, but again, old libraries) but it should run without problems if you use Java 7-9.

**Comment by EngyNasr** [comment]
I cannot thank you enough for your great support, thanks a lot, I will use
java 7 for the exceptions

Kind Regards,
Engy Nasr

**Comment by EngyNasr** [comment]
Hello,

I would like to thank you again for your great effort in AML, and kindly I
have some questions regarding AML.

1) If there is a possibility to understand more about the matchers used in
AML and how they really work in order to match, with there different
preferences and settings, I would be so grateful if you provided me with
these information or where to find them.

2) How are the percentages of that matched entities are calculated ?

3) Is there a way in AML to check super or sub class or is it just
equivalence relations between matched entities?


Thanks you so much in advance.

Kind Regards,
Engy Nasr

**Comment by cpesquita** [comment]
Dear Engy,

I invite you to read the following papers, as well as our OAEI yearly
submission papers published in the Ontology Matching workshop.
https://jbiomedsem.biomedcentral.com/articles/10.1186/s13326-017-0170-9
http://disi.unitn.it/~p2p/RelatedWork/Matching/Feriae_AgreementMakerLight13.pdf

I hope these make it easier for you to understand AML. Feel free to get
back to us with any questions.

Best regards,
Catia Pesquita
http://www.di.fc.ul.pt/~catiapesquita/

Professora Auxiliar
Departamento de Informática
Faculdade de Ciências da Universidade de Lisboa
