### ISSUE TITLE
io.github.firemaples.language and .translate not exists

### ISSUE THREAD

**Issue by mornsong** [AgreementMakerLight/AML-Project#13]
"D:\Program Files\Java\jdk-10.0.2\bin\java.exe" -Dmaven.multiModuleProjectDirectory=F:\code\AML-Project-master\AgreementMakerLight "-Dmaven.home=D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.3\plugins\maven\lib\maven3" "-Dclassworlds.conf=D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.3\plugins\maven\lib\maven3\bin\m2.conf" "-javaagent:D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.3\lib\idea_rt.jar=51214:D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.3\bin" -Dfile.encoding=UTF-8 -classpath "D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.3\plugins\maven\lib\maven3\boot\plexus-classworlds-2.5.2.jar" org.codehaus.classworlds.Launcher -Didea.version=2018.2.3 install
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for aml:aml:jar:2.1-SNAPSHOT
[WARNING] 'dependencies.dependency.systemPath' for edu.smu.tspell.wordnet:jaws:jar should not point at files within the project directory, ${project.basedir}/src/lib/jaws.jar will be unresolvable by dependent projects @ line 119, column 19
[WARNING] 'dependencies.dependency.systemPath' for org.gephi:gephi-toolkit:jar should not point at files within the project directory, ${project.basedir}/src/lib/gephi-toolkit.jar will be unresolvable by dependent projects @ line 126, column 19
[WARNING] 'dependencies.dependency.systemPath' for uk.ac.shef.wit:simmetrics:jar should not point at files within the project directory, ${project.basedir}/src/lib/simmetrics.jar will be unresolvable by dependent projects @ line 159, column 19
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building AgreementMakerLight 2.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ aml ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory F:\code\AML-Project-master\AgreementMakerLight\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ aml ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 119 source files to F:\code\AML-Project-master\AgreementMakerLight\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /F:/code/AML-Project-master/AgreementMakerLight/src/aml/knowledge/Translator.java:[31,37] 程序包io.github.firemaples.language不存在（not exists）
[ERROR] /F:/code/AML-Project-master/AgreementMakerLight/src/aml/knowledge/Translator.java:[32,39] 程序包io.github.firemaples.translate不存在（not exists）
[ERROR] /F:/code/AML-Project-master/AgreementMakerLight/src/aml/knowledge/Translator.java:[41,32] 找不到符号
  符号:   类 Language（No sign found   Symbol: class）
  位置: 类 aml.knowledge.Translator
[INFO] 3 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.587 s
[INFO] Finished at: 2019-04-16T15:28:39+08:00
[INFO] Final Memory: 24M/94M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project aml: Compilation failure: Compilation failure:
[ERROR] /F:/code/AML-Project-master/AgreementMakerLight/src/aml/knowledge/Translator.java:[31,37] 程序包io.github.firemaples.language不存在
[ERROR] /F:/code/AML-Project-master/AgreementMakerLight/src/aml/knowledge/Translator.java:[32,39] 程序包io.github.firemaples.translate不存在
[ERROR] /F:/code/AML-Project-master/AgreementMakerLight/src/aml/knowledge/Translator.java:[41,32] 找不到符号
[ERROR] 符号:   类 Language
[ERROR] 位置: 类 aml.knowledge.Translator
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Process finished with exit code 1

**Comment by AgreementMakerLight** [comment]
My apologies for this issue. We have been aware that some of the Maven dependencies were no longer available for some time, and we added them to the git repository as a temporary fix, but we forgot to update the pom.xml file accordingly.
We have now done so, and the issue should be solved, if not in the ideal manner.
