### ISSUE TITLE
problem with http://maven.yeezhao.com:8081/nexus/content/groups/public/ without user&password Could not resolve dependencies gephi

### ISSUE THREAD

**Issue by onetarik** [AgreementMakerLight/AML-Project#14]

**Comment by onetarik** [comment]
Hello,
I have the following error when trying to build with maven
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.317 s
[INFO] Finished at: 2019-06-12T16:23:19+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project aml: Could not resolve dependencies for project aml:aml:jar:2.1-SNAPSHOT: Failed to collect dependencies at org.gephi:gephi-toolkit:jar:0.8.2: Failed to read artifact descriptor for org.gephi:gephi-toolkit:jar:0.8.2: Could not transfer artifact org.gephi:gephi-toolkit:pom:0.8.2 from/to maven.yeezhao.com (http://maven.yeezhao.com:8081/nexus/content/groups/public/): Not authorized -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by AgreementMakerLight** [comment]
My apologies for this issue. We have been aware that some of the Maven dependencies were no longer available for some time, and we added them to the git repository as a temporary fix, but we forgot to update the pom.xml file accordingly.
We have now done so, and the issue should be solved, if not in the ideal manner.
