### ISSUE TITLE
Add input format to readme

### ISSUE THREAD

**Issue by afshinrahimi** [AgreementMakerLight/AML-Project#18]
Hi,
Thanks for the great work!
Is it possible to add the input format to the repo description please?
I'm trying to use AML, but not sure how I need to format my data.
Thanks.

**Comment by DanFaria** [comment]
Hi,
AML can match ontologies in any format supported by the OWL API, which includes a bunch of different OWL serializations (RDF/XML, OWL, TTL, NT, ...) plus SKOS.
I will add this to README.
Thanks for the feedback.
