### ISSUE TITLE
Nothing matched

### ISSUE THREAD

**Issue by luisenriqueramos1977** [AgreementMakerLight/AML-Project#21]
HI, 

I run the tool, and uploaded two different owl ontology, and nothing happens. Then, I uploaded two times the same ontologies, and nothing happens as well.

What should I be doing wrong?

Luis

**Comment by cpesquita** [comment]
Dear Luis,

After loading the ontologies you need to select the option to run the alignment job. If this does not solve your issue, please let us know which ontologies you are trying to align so we can replicate the issue.

Thank you for using AML.

**Comment by samsontu** [comment]
I ran AML using the GUI and found that, after specifying the source and target ontologies and clicking the "Open" button, the app hangs with the Console showing "Loading source ontology". Then I tried using the command line. The app appears to work, but no output file is generated. Appended below is the log of the CLI interaction. I am using an M1 MacBook Pro with Sonoma OS and running OpenJDK Runtime Environment (build 20.0.2+9-78).  

(base) samsons02114mbp:AML_v3.2 tu$ java -jar AgreementMakerLight.jar -s $dir/ontologies/ICD10-label.owl -t $dir/ontologies/ICD11-label.owl -o ICD10-11AML.rdf -a
Loading source ontology
http://purl.bioontology.org/ontology/ICD10 loaded in 1 seconds
Classes: 12318
Individuals: 0
Properties: 0
Loading target ontology
file:/Users/tu/Documents/Dropbox/Ontologies/ICD11.owl loaded in 3 seconds
Classes: 77036
Individuals: 0
Properties: 0
Direct Relationships: 99981
Running transitive closure on RelationshipMap
Transitive closure finished in 2 seconds
Extended Relationships: 704651
Disjoints: 0
Reading config.ini file
Finished!
Running Lexical Matcher
Finished in 1 seconds
Loading mediating ontology doid.owl
http://purl.obolibrary.org/obo/doid.owl loaded in 0 seconds
Running Mediating Cross-Reference Matcher using http://purl.obolibrary.org/obo/doid.owl
Finished in 0 seconds
doid.owl selected as a mediator
Loading mediating ontology uberon.owl
http://purl.obolibrary.org/obo/uberon.owl loaded in 2 seconds
Running Mediating Cross-Reference Matcher using http://purl.obolibrary.org/obo/uberon.owl
Finished in 0 seconds
uberon.owl discarded
Extending Alignment with String Matcher
Matching Children & Parents
Matching Siblings
Finished in 3 seconds
Running Obsoletion Filter
Finished in 0 seconds
Computing High-Level Structure Overlap
Finished in 0 seconds
Computing Neighbor Similarity
Finished in 0 seconds
Performing Selection
Finished in 0 seconds
Building Repair Map
Nothing to repair!
Alignment is coherent
(base) samsons02114mbp:AML_v3.2 tu$

**Comment by samsontu** [comment]
I was able to receive output after I added the following in my java call: 
java --add-opens java.base/java.lang=ALL-UNNAMED -Xms2G -Xmx6G -DentityExpansionLimit=100000000 -jar AgreementMakerLight.jar ...
Thanks.

**Comment by cpesquita** [comment]
Happy to see you have it working now!
