### ISSUE TITLE
mvn install error

### ISSUE THREAD

**Issue by Seondong** [AgreementMakerLight/AML-Project#4]
I tried to run AML from the source (command: mvn install), however it failed to build.

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.323 s
[INFO] Finished at: 2015-12-30T17:32:28+09:00
[INFO] Final Memory: 8M/241M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project aml: Could not resolve dependencies fo
r project aml:aml:jar:2.1-SNAPSHOT: Failed to collect dependencies at org.gephi:
gephi-toolkit:jar:0.8.2: Failed to read artifact descriptor for org.gephi:gephi-
toolkit:jar:0.8.2: Could not transfer artifact org.gephi:gephi-toolkit:pom:0.8.2
 from/to gephi-nexus (http://nexus.gephi.org/nexus/content/repositories/releases
): nexus.gephi.org: Unknown host nexus.gephi.org -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException


```

**Comment by AgreementMakerLight** [comment]
My apologies!
Apparently Gephi moved to a new Maven repository and we failed to notice it.
I have just updated the pom file with the new Gephi repository, so it should build correctly now.
Please let me know if you have further issues.

**Comment by Seondong** [comment]
Thanks. I cloned updated version, but still got an error from gephi. Please check that.
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.659 s
[INFO] Finished at: 2015-12-30T20:10:17+09:00
[INFO] Final Memory: 9M/241M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project aml: Could not resolve dependencies for project aml:aml:jar:2.1-SNAPSHOT: Could not
 find artifact org.gephi:gephi-toolkit:jar:0.8.2 in oss-sonatype (https://oss.sonatype.org/content/repositories/snapshots/) -
> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by AgreementMakerLight** [comment]
Unfortunately it seems that Gephi's new official Maven repository only has version 0.9 of the toolkit.
I did some testing and found that it is not fully compatible with the version we have (0.8.2).
After some searching, I was able to find a Maven repository that has version 0.8.2 available.
I have updated the pom file with this alternative repository. Hopefully that should do the trick.
Please let me know if it works!

**Comment by eliohb** [comment]
hello i am trying to build the project but i have the following error:
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:19 min
[INFO] Finished at: 2019-02-26T11:34:16+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project aml: Could not resolve dependencies fo
r project aml:aml:jar:2.1-SNAPSHOT: Failed to collect dependencies at org.gephi:
gephi-toolkit:jar:0.8.2: Failed to read artifact descriptor for org.gephi:gephi-
toolkit:jar:0.8.2: Could not transfer artifact org.gephi:gephi-toolkit:pom:0.8.2
 from/to maven.yeezhao.com (http://maven.yeezhao.com:8081/nexus/content/groups/p
ublic/): Connection reset -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException
