### ISSUE TITLE
ISUB QUERY

### ISSUE THREAD

**Issue by shivangihpatel** [AgreementMakerLight/AML-Project#6]
to find sub string similarity there are three terms used : comm , diff and improvement term. is it possible to replace any of the term with other method or metric? what does p represent in equation of diff?

**Comment by DanFaria** [comment]
Hi,
We are not the authors of the ISub string similarity algorithm - Giorgios Stoilos is, as you can see in the copyright information. As such, questions regarding the algorithm would be best addressed to him.
That said, here is my input on your questions:
1) I'm not sure what you mean by "possible". There is nothing preventing you from replacing any of the terms you mentioned or making modifications to them, so in that sense it is evidently possible. However, changing ISub in that manner would lead to essentially a different metric, so the true question is whether it will be more effective than ISub (i.e., measure string similarity more accurately in the context of ontologies). As to that, I have no idea - I see no harm in trying, but ISub works quite well, so I would say it won't be easy to improve upon it. 
2) p is simply a weighting factor
