### ISSUE TITLE
About skos:concept doesnt load ConceptScheme

### ISSUE THREAD

**Issue by savacano28** [AgreementMakerLight/AML-Project#9]
HI! Thank you so much for your projet! now I'm making some alignements with it but I have a problem with my skos rdf file, I dont why AML cant be load the concepts which I defined in my file, I try many solutions but the issue isn't resolved. I attached my file and I'd appreciate so much your help :).  (I load in .txt but it's .rdf)
[t_istex_skosconcept.txt](https://github.com/AgreementMakerLight/AML-Project/files/1863284/t_istex_skosconcept.txt)

**Comment by DanFaria** [comment]
Hi!
I'll try to look into your file within the next few days, and will get back to you as soon as I have some feedback.
Best!

**Comment by savacano28** [comment]
Thank u so much! :D ^^!

**Comment by DanFaria** [comment]
Hi!
There were a few problems with your rdf file, in particular with the resources you listed under exactMatch declarations, which resulted in the file not being valid rdf, and thus not parseable by the OWL API that AML relies on.
Concretely, you cannot include "&quot;" in a URI nor can you list several resources separated by a semi-colon under a single resource field. If you correct these problems, as I have done in the attached file, AML will be able to read your ontology.

Please also note that your usage of skos:exactMatch to reference external resources is not a good practice: skos:exactMatch is an owl:ObjectProperty that should used to relate skos:Concepts declared in your thesaurus (or imported by it). AML will not be able to adequately process these exactMatches or used them in any way.

Also keep in mind that AML translates SKOS into an OWL approximation (e.g., it treats skos concepts as if they were owl classes, even though they are technically instances of "skos:Concept" which is formally an "owl:Class") but this translation is not complete wrt SKOS syntax and may need refinement. It is a symptom of our very limited contact with SKOS matching problems.

Best!

[t_istex_skosconcept.txt](https://github.com/AgreementMakerLight/AML-Project/files/1869157/t_istex_skosconcept.txt)

**Comment by savacano28** [comment]
Thank you so much for your help! that's my first file in skos and I'm gonna keep in mind your advices. Thanks again! :)
